<a href="https://colab.research.google.com/github/Shashikala-s/into-LLM/blob/main/sheet_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML and NLP libraries

**torch** : Pytorch- Deep learning framework  . Allows for tensor(multi dimentional array) computations and building/training neural netowrks

**transformers** : From Hugging face -Provide pre-train model like GPT , BERT for NLP task (calssification , translation , summarization )

**datasets** : From Hugging Face -Give access to wide range of NLP datasets abd tools for processing and eveluation .



# LangChain Ecosystem

**Langchain-community** :
Community contributed integrations for LangChan frameworks which used to build apps with language models (LLMs) including agents , tools and memeory

**langchain_nvidia_ai_endpoints**  :
Integration for Nvidia foundation models with Langchain . It coneects Langchain to Nvidia' colud hosted AI services

# AI tooling and Utilites

**python-dotenv**  : Load environment vaiables from .env file . Useful to manage API keys and secrets

**torchrl**  : Library form PyTorch for Reinforcement Learning (RL) . It  provides tools and environments for training RL agents

**llama-index** : helps connects LLMs to structured or unstructured data such as documents or databases to create retrival based app like custom GPT .

**bertviz** :  Visualization tool for BERT and Transformer models .  It helps in understanding attention mechanism with transformer models

**wikipedia** : Python wrapper , allow fetch articles from Wikipedia

In [ ]:
!pip install fsspec==2025.3.0 gcsfs==2025.3.0



  Using cached fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Using cached fsspec-2025.3.0-py3-none-any.whl (193 kB)
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: gcsfs
    Found existing installation: gcsfs 2025.3.2
    Uninstalling gcsfs-2025.3.2:
      Successfully uninstalled gcsfs-2025.3.2


In [ ]:
!python -m venv torch_env
!source torch_env/bin/activate  # Windows: torch_env\Scripts\activate

# Install matching versions:
!pip install datasets==3.6.0 fsspec==2025.3.0 gcsfs==2025.3.0


Error: Command '['/content/torch_env/bin/python3', '-m', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
/bin/bash: line 1: torch_env/bin/activate: No such file or directory


In [ ]:
!pip install torch transformers datasets langchain-community langchain_nvidia_ai_endpoints==0.3.9 python-dotenv==1.1.0 torchrl llama-index bertviz wikipedia

In [ ]:
import torch
from transformers import AutoTokenizer
from langchain.tools import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper

In [ ]:
if torch.cuda.is_available():
  device =torch.device("cuda")
  print(f"Device :{device}")

elif torch.backends.mps.is_available():
  device = torch.device("mps")
  print(f"Device :{device}")

else:
  device = torch.device("cpu")
  print(f"Device :{device}")

Device :cpu


In [ ]:
#test Pytorch
x= torch.rand(5,3).to(device)
print(x)
print(x.shape)
print(x.device)

tensor([[0.9126, 0.3039, 0.2345],
        [0.1867, 0.7433, 0.2689],
        [0.6047, 0.4253, 0.9009],
        [0.1281, 0.4872, 0.5073],
        [0.7098, 0.9262, 0.9775]])
torch.Size([5, 3])
cpu


In [ ]:
y=torch.ones(5,3).to(device)
print(y)
print(y.shape)
print(y.device)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([5, 3])
cpu


In [ ]:
b=torch.full((5,3),5).to(device)
print(b)
print(b.shape)
print(b.device )

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])
torch.Size([5, 3])
cpu


In [ ]:
#multiply x and y(element wise multipication)
z=x*y
print(z)

tensor([[0.9126, 0.3039, 0.2345],
        [0.1867, 0.7433, 0.2689],
        [0.6047, 0.4253, 0.9009],
        [0.1281, 0.4872, 0.5073],
        [0.7098, 0.9262, 0.9775]])


In [ ]:
# x @ y( matrix multipication : linear algebra operarion  )
#columns in x must equal the number of rows in y
# use transpose : x(5, 3) and x.T(3,5 = flip rows and columns)
# now x.T(3.5) and y ( 5, 3)

#x @ y.T: similarity between rows of x and y.

#x.T @ y: computes feature-wise correlation across rows.

z1= x.T @ y
print(z1)

print('\n')

z2 =x @ y.T
print(z2)

tensor([[2.5419, 2.5419, 2.5419],
        [2.8858, 2.8858, 2.8858],
        [2.8891, 2.8891, 2.8891]])


tensor([[1.4510, 1.4510, 1.4510, 1.4510, 1.4510],
        [1.1989, 1.1989, 1.1989, 1.1989, 1.1989],
        [1.9308, 1.9308, 1.9308, 1.9308, 1.9308],
        [1.1227, 1.1227, 1.1227, 1.1227, 1.1227],
        [2.6135, 2.6135, 2.6135, 2.6135, 2.6135]])


In [ ]:
#test langchain
wikipedia=WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())
wikipedia.run('Attention is all you need')

'Page: Attention Is All You Need\nSummary: "Attention Is All You Need" is a 2017 landmark research paper in machine learning authored by eight scientists working at Google. The paper introduced a new deep learning architecture known as the transformer, based on the attention mechanism proposed in 2014 by Bahdanau et al. It is considered a foundational paper in modern artificial intelligence, and a main contributor to the AI boom, as the transformer approach has become the main architecture of a wide variety of AI, such as large language models. At the time, the focus of the research was on improving Seq2seq techniques for machine translation, but the authors go further in the paper, foreseeing the technique\'s potential for other tasks like question answering and what is now known as multimodal Generative AI.\nThe paper\'s title is a reference to the song "All You Need Is Love" by the Beatles. The name "Transformer" was picked because Jakob Uszkoreit, one of the paper\'s authors, liked

In [ ]:
#test pre train language models
# download and load GPT-2 tokenizer

tokenizer_gpt2=AutoTokenizer.from_pretrained("gpt2")
text="Attention is all you need "

#return_tensors="pt"=> return ytpe
#tokenize the text(convert string into tensor of token IDs)
input_ids=tokenizer_gpt2(text, return_tensors="pt").to(device)
print(input_ids)

{'input_ids': tensor([[8086, 1463,  318,  477,  345,  761,  220]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1]])}
